function printResults(fov, unit)
    %
    % USAGE::
    %
    %  printResults(fov, unit)
    %
    % (C) Copyright 2022 CPP lab developpers

    fprintf(1, ['\n\n' repmat('-', 1, 80) '\n']);

    fprintf(1, ['Field of view in %s:\n' ...
                ' top left: %i %i\n', ...
                ' bottom right: %i %i\n\n'], ...
            upper(unit), ...
            fov(2), fov(1), ...
            fov(4), fov(3));

    fprintf(1, ['Field of view in %s:\n', ...
                ' width: %i\n', ...
                ' height: %i\n\n'], ...
            upper(unit), ...
            fovWidth(fov), ...
            fovHeight(fov));

end
