function printResults(fov, unit)
    %
    % USAGE::
    %
    %  printResults(fov, unit)
    %
    % (C) Copyright 2022 CPP lab developpers

    fprintf(1, ['Field of view in %s:\n' ...
                ' top left: %i %i\n', ...
                ' bottom right: %i %i\n\n'], ...
            unit, ...
            fov(1), fov(2), ...
            fov(3), fov(4));

    fprintf(1, ['Field of view in %s:\n', ...
                ' width: %i\n', ...
                ' height: %i\n\n'], ...
            unit, ...
            fovWidth(fov), ...
            fovHeight(fov));

end
